services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - myWallet-back/.env
    volumes:
      - mongo-volume:/var/lib/mongodb/data

  node:
    container_name: node
    build: ./myWallet-back
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongo
    env_file:
      - myWallet-back/.env

  react:
    container_name: react
    build: ./myWallet-front
    volumes:
      - react-volume:/var/www/html

  nginx:
    container_name: nginx_app
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - mongo
      - node
      - react

volumes:
  mongo-volume:
  react-volume:
